changed to is_user_exist
if not await db.user_exist(message.from_user.id): #db add use and exist checking AttributeError: 'Database' object has no attribute 'user_exist'